### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by pathtofile** [microsoft/project-freta#7]
Ran a basic pip install and run:

```bash
$> freta image formats
ERROR:nsv-backend:request did not succeed: HTTP 500 -
Traceback (most recent call last):
  File "C:\testing\venv\Scripts\freta-script.py", line 33, in <module>
    sys.exit(load_entry_point('freta==0.0.15', 'console_scripts', 'freta')())
  File "C:\testing\venv\lib\site-packages\freta\__main__.py", line 16, in main
    return execute_api(Freta(), [Endpoint], __version__)
  File "C:\testing\venv\lib\site-packages\freta\cli.py", line 315, in execute_api
    result = call_func(args.func, args)
  File "C:\testing\venv\lib\site-packages\freta\cli.py", line 38, in call_func
    return func(**myargs)
  File "C:\testing\venv\lib\site-packages\freta\api.py", line 109, in formats
    return self.backend.request("GET", "image_formats")
  File "C:\testing\venv\lib\site-packages\freta\backend.py", line 233, in request
    raise Error(
freta.backend.Error: 'request did not succeed: HTTP 500 - '
```

**Comment by bmc-msft** [comment]
Acknowledged.

Our research portal is currently offline and we're working to bring it back up.

**Comment by bmc-msft** [comment]
The service is back online, though the SDK has been rewritten in Rust.  We will be investigating providing a Python SDK built on top of the Rust SDK in the future.
